name: Crawler Movie
on:
  schedule:
    - cron: "0 */3 * * *" # Chạy mỗi 3 tiếng
  workflow_dispatch:      # Cho phép bấm nút "Run" thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # QUAN TRỌNG: Cấp quyền ghi file
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run Crawler
        run: python crawler.py
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add movies_database.json movies.m3u
          git commit -m "Auto-update movie list" || echo "No changes to commit"
          git push
